### ISSUE TITLE
DIContainer is not a constructor

### ISSUE THREAD

**Issue by itmarck** [radzserg/rsdi-legacy#23]
**Summary**

I was trying to use the package following the README example, but after everything was good and run the server I got the following error.

```
const container = new DIContainer()
                    ^

TypeError: DIContainer is not a constructor
    at forge (file:///D:/code/src/container.js:13:21)
    at file:///D:/code/src/index.js:10:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

I saw the package implementation and it is not a constructor actually, but a IIFE.

Note: If switch the line to `const container = DIContainer()` got an error that says that it's not a function instead.

Not sure how to make the package work with this issue in runtime. I'd appreciate any help.

**Comment by itmarck** [comment]
I found a way to solve this but not sure if it is a proper one. I guess it could be related to the fact that I'm using pure Javascript.

The class should be instantiated as follows.

```js
const container = new DIContainer.default();
```

Doing this causes an error with the `ts` declaration because it doesn't exists. But could use `// @ts-ignore` for skip the linting only in the line.

**Comment by radzserg** [comment]
Sorry, I didn't mean to publish `3.0.0-alpha.1` I'm working on a fix.
